name: Compile Redhat Binaries

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker image tag'
        required: true
        default: "latest"
      branch:
        description: 'Branch to build binaries for'
        required: true
        default: "develop"
      services:
        description: 'Services to run (comma-separated or all)'
        required: true
        default: '--all'
      githubtoken:
          description: 'github token'
          required: true
          default: 'XXXXXX'
      docker_binaries_for:
          description: 'Prod or Dev repo'
          required: true
          default: dev
          type: choice
          options:
          - dev
          - prod
      credentials:
        description: 'Repo config - docker credentials'
        required: false
        default: 'DOCKERCRE'

jobs:
  run_docker_container:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v4

      # Paso 2: Imprimir argumentos
      - name: Docker arguments
        run: |
         echo "Image Tag: ${{ inputs.image_tag }}"

      - name: Printing variables
        run: |
          echo "Image Tag: ${{ inputs.image_tag }}"
          echo "Branch: ${{ inputs.branch }}"
          echo "Services: ${{ inputs.services }}"
          echo "Credentials: ${{ inputs.credentials }}"
          echo "Docker binaries: ${{ inputs.docker_binaries_for }}"

      # Paso 4: Levantar el contenedor con los argumentos
      - name: Run Docker Container
        run: |
          docker run -a stdout -a stderr \
            --rm \
            --name my-container \
            -e BRANCH=${{ inputs.branch }} \
            -e GITTOKEN=${{ inputs.githubtoken }} \
            -e ENV=${{ inputs.docker_binaries_for }} \
            -e SERVICES="${{ inputs.services }}" \
            guarddogai/binaries:${{ inputs.image_tag }}
